function handles = SetDAQ(handles)

%% DAQ card setup
handles.hDaqSetupPnl = uipanel('Parent', handles.hfigM,...
                        'Title', 'Acquisition Settings',...
                        'Fontweight', 'bold',...
                        'Units', 'normalized',...
                        'Fontsize', 12, ...
                        'Position', [.525, .25, .45, .25]);                
                    
                  
                            
handles.hImgRootLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Image name:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .75, .35, .15],...
                         'Style','text');
                     
handles.hImgRootFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'ImgNameRoot'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.35, .75, .57, .15],...
                         'Style','edit',...
                         'Callback',{@updateImgRoot_Callback, handles});
                     
                     
handles.hSmplRtLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Sampling [MHz]:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .575, .3, .15],...
                         'Style','text');
                     
handles.hSmplRtFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'SamplingRateMHz'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.35, .575, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateSamplingRateMHz_Callback, handles});
                     
handles.hRcrLenLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Record [Points]:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.52, .4, .3, .15],...
                         'Style','text');
                     
handles.hRcrLenFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'AcqLengthPoint'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.82, .4, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateAcqLengthPoint_Callback, handles});                     
                     

handles.hTrigLvlLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Trig level:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .4, .3, .15],...
                         'Style','text');
                     
handles.hTrigLvlFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'AtrigLevel'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.35, .4, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateAtrigLevel_Callback, handles});
                     
handles.hPreTrigLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Delay [usec]:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.52, .575, .3, .15],...
                         'Style','text');
                     
handles.hPreTrigFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'PreTrigSampl'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.82, .575, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updatePreTrigSampl_Callback, handles}); 
                     
handles.hOffsetLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Offset CH1/2/3/4:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .225, .3, .15],...
                         'Style','text');
                     
handles.hCh1OffstFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'OffsetCH1'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.35, .225, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateOffsetCH1_Callback, handles}); 
       
handles.hCh2OffstFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'OffsetCH2'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.51, .225, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateOffsetCH2_Callback, handles});
                     
handles.hCh3OffstFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'OffsetCH3'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.67, .225, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateOffsetCH3_Callback, handles}); 

 handles.hCh4OffstFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'OffsetCH4'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.83, .225, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateOffsetCH4_Callback, handles});                    
                     
handles.hOffsetLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Channel option:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .05, .6, .15],...
                         'Style','text');                     

pulldownValue = getappdata(0, 'Channeloption'); %read the channel option from appdata
% select the pulldown index based on channeloption value
if pulldownValue == 7
    pulldownValue = 1;
elseif pulldownValue == 3
    pulldownValue = 2;
elseif pulldownValue == 0
    pulldownValue = 3;
end
handles.hChOptFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'string',{'SINGLE_CH3';'DUAL_1_3';'QUAD'},...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'position',[.35, .05, .6, .15],...  
                         'style','pop',...
                         'value',pulldownValue,...
                         'Callback',{@updateChanneloption_Callback, handles});                     
 
end
% handles.hFetchImgDataBtn = uicontrol('Parent', handles.hDaqSetupPnl,...
%                                 'String', 'Fetch image data',...
%                                 'Units','normalized',...
%                                  'Fontsize',9,...
%                                  'Fontweight', 'normal',...
%                                  'HorizontalAlignment', 'center',...
%                                  'Position',[.05, .05, .9, .18],...
%                                  'Style','togglebutton',...
%                                 'Callback',{@FetchImgData_Callback, handles})

function updateImgRoot_Callback(src, event, handles)
    name = get(src, 'String');
    if isempty(regexp(name, '[/\*:?"<>|0-9]', 'once'))
        setappdata(0, 'ImgNameRoot', name);
    else
        errordlg('Invalid file name. Try again.');
        set(src, 'String', getappdata(0, 'ImgNameRoot'));
    end
    
end

function updateSamplingRateMHz_Callback(src, event, handles)
    rate = get(src, 'String');
    rate = str2num(rate);
    channeloption = getappdata(0, 'Channeloption');
    if (channeloption == 3 && rate > 1500 || rate < 200)
        errordlg('Invalid sampling rate. For Dual channels enter a rate between 200 and 1500 MHz.');
        set(src, 'String', num2str(getappdata(0,'SamplingRateMHz')));
    elseif (channeloption == 0 && rate > 500 || rate < 200)
        errordlg('Invalid sampling rate. For Quad channels enter a rate between 200 and 500 MHz.')
        set(src, 'String', num2str(getappdata(0,'SamplingRateMHz')));
    else
       setappdata(0,'SamplingRateMHz', rate);
    end
end

function updateAcqLengthPoint_Callback(src, event, handles)
    len = get(src, 'String');
    len = str2num(len);
    if (len < 200 || len > 20000)
        errordlg('Invalid record length. Must be between 200 and 20000 Points');
        set(src, 'String', num2str(getappdata(0, 'AcqLengthMicroSec')));
    else
        setappdata(0, 'AcqLengthPoint', len);
    end
end


function updateAtrigLevel_Callback(src, event, handles)
    levl = get(src, 'String');
    levl = uint16(str2num(levl));
    if (levl < 0 || levl > 255)
        errordlg('Invalid record length. Must be between 0 and 255');
        set(src, 'String', num2str(getappdata(0, 'AtrigLevel')));
    else
        setappdata(0, 'AtrigLevel', levl);
    end
end

function updatePreTrigSampl_Callback(src, event, handles)
    pretrig = get(src, 'String');
    pretrig = str2num(pretrig);
    if (pretrig < -10 || pretrig > 30 || isempty(pretrig))
        errordlg('Invalid tigger delay. Must be between -10 usec and 30 usec');
        set(src, 'String', num2str(getappdata(0, 'PreTrigSampl')));
    
    else
        % convert pretrig in usec to sample count
        setappdata(0, 'PreTrigSampl', pretrig);
    end
end

function OpenImageFolder_Callback(src, event, handles)
    folder_name = uigetdir(getappdata(0, 'datadir'));
    set(src, 'String', strrep(folder_name, [getappdata(0, 'datadir'),'\'], ''));
    setappdata(0, 'Display_Image', folder_name);
    makeImgFromData(folder_name);
end

%% setting DC offset
function updateOffsetCH1_Callback(src, event, handles)
    offsettxt = get(src, 'String');
    offset = round(str2num(offsettxt));
    if (offset < 0 | offset > 4095)
        errordlg('Invalid offset value. Must be an integer between 0 and 4095');
        set(src, 'String', num2str(getappdata(0, 'OffsetCH1')));
    end
    setDCOffset(handles.phBrd, 1, offset); %% setting offset for CH1
    setappdata(0, 'OffsetCH1', offset);
end

function updateOffsetCH2_Callback(src, event, handles)
    offsettxt = get(src, 'String');
    offset = round(str2num(offsettxt));
    if (offset < 0 | offset > 4095)
        errordlg('Invalid offset value. Must be an integer between 0 and 4095');
        set(src, 'String', num2str(getappdata(0, 'OffsetCH2')));
    end
    setDCOffset(handles.phBrd, 2, offset); %% setting offset for CH2
    setappdata(0, 'OffsetCH2', offset);
end

function updateOffsetCH3_Callback(src, event, handles)
    offsettxt = get(src, 'String');
    offset = round(str2num(offsettxt));
    if (offset < 0 | offset > 4095)
        errordlg('Invalid offset value. Must be an integer between 0 and 4095');
        set(src, 'String', num2str(getappdata(0, 'OffsetCH3')));
    end
    setDCOffset(handles.phBrd, 3, offset); %% setting offset for CH3
    setappdata(0, 'OffsetCH3', offset);
end

function updateOffsetCH4_Callback(src, event, handles)
    offsettxt = get(src, 'String');
    offset = round(str2num(offsettxt));
    if (offset < 0 | offset > 4095)
        errordlg('Invalid offset value. Must be an integer between 0 and 4095');
        set(src, 'String', num2str(getappdata(0, 'OffsetCH4')));
    end
    setDCOffset(handles.phBrd, 4, offset); %% setting offset for CH4
    setappdata(0, 'OffsetCH4', offset);
end
