        
%% connection pannel
handles.hCnctPnl = uipanel('Parent', handles.hfigM,...
                        'Title', 'Connection',...
                        'Fontweight', 'bold',...
                        'Units', 'normalized',...
                        'Position', [.05 .9 .9 .08]);
                    
handles.hCnctStatsLbl = uicontrol('Parent', handles.hCnctPnl,...
                         'String','Status :',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.05, 0, .2, 1],...
                         'Style','text');
                     
handles.hCnctStatsFld = uicontrol('Parent', handles.hCnctPnl,...
                         'String','Disconnected. Ready to connect...',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'bold',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.3, .0, .7, 1],...
                         'Style','text'); 
                    
%% Image params pannel
handles.hImgParamPnl = uipanel('Parent', handles.hfigM,...
                        'Title', 'Image Parameters',...
                        'Fontweight', 'bold',...
                        'Units', 'normalized',...
                        'Position', [.05 .7 .9 .18]);
                    
handles.hHrzPixLbl =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','Horiz. Pixels:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.05, .7, .3, .25],...
                         'Style','text');
                     
handles.hHrzPixFld =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','---',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.36, .7, .14, .25],...
                         'Style','text');
                     
handles.hVertLineLbl =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','Vert. Lines:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.525, .7, .3, .25],...
                         'Style','text');
                     
handles.hVertLineFld =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','---',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.84, .7, .14, .25],...
                         'Style','text');
                     
                     
handles.hFlybkLbl =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','Flyback Pix:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.05, .45, .3, .25],...
                         'Style','text');
                     
handles.hFlybkFld =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','---',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.36, .45, .14, .25],...
                         'Style','text'); 
                     
 
handles.hLineAvrgLbl =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','Line Averg:',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.525, .45, .3, .25],...
                         'Style','text');
                     
handles.hLineAvrgFld =  uicontrol('Parent', handles.hImgParamPnl,...
                         'String','---',...
                         'Units','normalized',...
                         'Fontsize',10,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.84, .45, .14, .25],...
                         'Style','text');
                     
                     
                    
%% Acquisition status
handles.hAcqStatsPnl = uipanel('Parent', handles.hfigM,...
                        'Title', 'acquisition status',...
                        'Fontweight', 'bold',...
                        'Units', 'normalized',...
                        'Position', [.05 .6 .9 .08]);
                    
handles.hAcqStatsLbl = uicontrol('Parent', handles.hAcqStatsPnl,...
                         'String','Status :',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'bold',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.05, .00, .2, 1],...
                         'Style','text');
                     
handles.hAcqStatsFld = uicontrol('Parent', handles.hAcqStatsPnl,...
                         'String','Waiting for connection...',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'bold',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.3, .00, .7, 1],...
                         'Style','text'); 
                    
%% Display
handles.hDispPnl = uipanel('Parent', handles.hfigM,...
                        'Title', 'image display',...
                        'Fontweight', 'bold',...
                        'Units', 'normalized',...
                        'Position', [.05 .4 .9 .18]);
handles.hImgSlctLbl = uicontrol('Parent', handles.hDispPnl,...
                         'String','Open Image:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .65, .25, .35],...
                         'Style','text');
                     
handles.hImgSlctFld = uicontrol('Parent', handles.hDispPnl,...
                         'String','Select image folder',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.3, .65, .65, .35],...
                         'Style','togglebutton',...
                         'Callback',{@OpenImageFolder_Callback, handles});
                    
                    
                    
%% DAQ card setup
handles.hDaqSetupPnl = uipanel('Parent', handles.hfigM,...
                        'Title', 'Acquisition setup',...
                        'Fontweight', 'bold',...
                        'Units', 'normalized',...
                        'Position', [.05 .05 .9 .34]);
                    
                    
handles.hServerIPLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Server IP/Port:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .85, .35, .15],...
                         'Style','text');
                     
handles.hServerIPFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'serverIP'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.31, .85, .27, .15],...
                         'Style','edit',...
                         'Callback',{@updateServerIP_Callback, handles});
                     
                     
handles.hServerPortFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'serverPort'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.59, .85, .14, .15],...
                         'Style','edit',...
                         'Callback',{@updateServerPort_Callback, handles});
                     
                    
handles.hServerCnctBtn = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Connect',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'right',...
                         'Position',[.75, .85, .2, .15],...
                         'Style','pushbutton',...
                         'Callback',{@connect2Server_Callback, handles}); 
                     
                            
handles.hImgRootLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Image name:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .7, .35, .15],...
                         'Style','text');
                     
handles.hImgRootFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'ImgNameRoot'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.4, .7, .55, .15],...
                         'Style','edit',...
                         'Callback',{@updateImgRoot_Callback, handles});
                     
                     
handles.hSmplRtLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Sampling [MHz]:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .55, .3, .15],...
                         'Style','text');
                     
handles.hSmplRtFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'SamplingRateMHz'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.35, .55, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateSamplingRateMHz_Callback, handles});
                     
handles.hRcrLenLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Record [usec]:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.52, .55, .3, .15],...
                         'Style','text');
                     
handles.hRcrLenFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'AcqLengthMicroSec'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.82, .55, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateAcqLengthMicroSec_Callback, handles});                     
                     

handles.hTrigLvlLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Trig level:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .4, .3, .15],...
                         'Style','text');
                     
handles.hTrigLvlFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'AtrigLevel'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.35, .4, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateAtrigLevel_Callback, handles});
                     
handles.hPreTrigLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Delay [usec]:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.52, .4, .3, .15],...
                         'Style','text');
                     
handles.hPreTrigFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'PreTrigSampl'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.82, .4, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updatePreTrigSampl_Callback, handles}); 
                     
handles.hOffsetLbl = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String','Offset CH1/Ch3:',...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.05, .25, .3, .15],...
                         'Style','text');
                     
handles.hCh1OffstFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'OffsetCH1'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.4, .25, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateOffsetCH1_Callback, handles}); 
                     
handles.hCh3OffstFld = uicontrol('Parent', handles.hDaqSetupPnl,...
                         'String',getappdata(0, 'OffsetCH3'),...
                         'Units','normalized',...
                         'Fontsize',9,...
                         'Fontweight', 'normal',...
                         'HorizontalAlignment', 'left',...
                         'Position',[.6, .25, .12, .15],...
                         'Style','edit',...
                         'Callback',{@updateOffsetCH3_Callback, handles}); 
                     
handles.hFetchImgDataBtn = uicontrol('Parent', handles.hDaqSetupPnl,...
                                'String', 'Fetch image data',...
                                'Units','normalized',...
                                 'Fontsize',9,...
                                 'Fontweight', 'normal',...
                                 'HorizontalAlignment', 'center',...
                                 'Position',[.05, .05, .9, .18],...
                                 'Style','togglebutton',...
                                'Callback',{@FetchImgData_Callback, handles});
                            
